#!/bin/bash

# Create config.js from environment variables
cat > config.js << EOF
// config.js - Auto-generated during Render build
// WARNING: Do not edit this file directly

const KRO_CONFIG = {
    // Single API URL for all services
    API_URL: '$API_URL',
    
    // Secret token for API authentication
    API_SECRET_TOKEN: '$API_SECRET_TOKEN',
    
    // Your business details
    COMPANY_NAME: 'K.R.O Cleaning Service',
    COMPANY_PHONE: '$COMPANY_PHONE',
    COMPANY_EMAIL: '$COMPANY_EMAIL',
    
    // Currency settings
    CURRENCY: '₦',
    CURRENCY_CODE: 'NGN',
    
    // Version
    VERSION: '1.0.0'
};

window.KRO_CONFIG = KRO_CONFIG;
EOF

echo "config.js generated successfully!"