#!/bin/bash

# Create config.js from environment variables
cat > config.js << EOF
// config.js - Auto-generated during Render build
// WARNING: Do not edit this file directly

const KRO_CONFIG = {
    GOOGLE_SCRIPT_URL: '$GOOGLE_SCRIPT_URL',
    API_SECRET_TOKEN: '$API_SECRET_TOKEN',
    COMPANY_NAME: 'K.R.O Cleaning Service',
    COMPANY_PHONE: '$COMPANY_PHONE',
    COMPANY_EMAIL: '$COMPANY_EMAIL',
    CURRENCY: '$CURRENCY',
    CURRENCY_CODE: 'NGN',
    ENABLE_GOOGLE_SHEETS: $ENABLE_GOOGLE_SHEETS,
    VERSION: '1.0.0'
};

window.KRO_CONFIG = KRO_CONFIG;
EOF

echo "config.js generated successfully!"